# prefix for output filenames
name: urmel
# debug mode with more output
debug: False
# write new initial state
new_init_scenario: False
# write problem files in the lp-format?
write_lp: False
# write solution files in the sol-format?
write_sol: False
# write irreducible infeasibility set if problem is infeasible?
write_ilp: False
# write wheel maps with gnuplot?
gnuplot: False
# console output?
urmel_console_output: False
# gurobi logfile
grb_logfile: '' #gurobi.log
# gurobi console output
grb_console: False
# contour output (net- and state-files in contour folder)
contour_output: False
# how often new trader nomination comes (number of timesteps)
nomination_freq: 8
# controlling random nomination values [start(opt),stop,step(opt)]
randrange: [0,1101,50]
# upper bound for the nomination of EH if scenario not completely random
upper_nom_EH: 550
# lower bound for the nomination of EH if scenario not completely random
lower_nom_EH: 250
# upper bound for the nomination of EN if scenario not completely random
upper_nom_EN: 850
# lower bound for the nomination of EN if scenario not completely random
lower_nom_EN: 550
# activation function for the hidden layers of the NN (tanh/sigmoid)
activ_fn: 'tanh'

