# prefix for output filenames
name: urmel
# debug mode with more output
debug: False
# write new initial state
new_init_scenario: True
# write problem files in the lp-format?
write_lp: False
# write solution files in the sol-format?
write_sol: True
# write irreducible infeasibility set if problem is infeasible?
write_ilp: True
# write wheel maps with gnuplot?
gnuplot: True
# console output?
urmel_console_output: False
# gurobi logfile
grb_logfile: gurobi.log
# gurobi console output
grb_console: False
# contour output (net- and state-files in contour folder)
contour_output: True
# how often new trader nomination comes (number of timesteps)
nomination_freq: 8
# controlling random nomination values [start(opt),stop,step(opt)]
randrange: [0,1101,50]
# Is AI control active?
ai: False
